### ISSUE TITLE
Does not compile for me

### ISSUE THREAD

**Issue by damiaan** [shsajjadi/OctaveUnimplemented#1]
running 
mkoctfile graydist.cc

I get errors and warnings 

graydist.cc:1001:11: error: unable to deduce ‘std::initializer_list<auto>&&’ from ‘{1, dims.dim_vector::operator()(((int)k))}’
 1001 |           for (octave_idx_type pad : {1, dims(k)})
      |           ^~~

and 

graydist.cc:1234:3: warning: control reaches end of non-void function [-Wreturn-type]
graydist.cc: In function ‘octave_value_list image::dispatch2(const octave_value_list&, int, const ImageType&, int, Args ...) [with ResultType = FloatNDArray; IndexType = int

My first attempt at mkoctfile, so changes are i am missing something quite basic here

>> edit: it compiles after changing line 1001 
from 
`          for (octave_idx_type pad : {1, dims(k)})
`to
`          for (octave_idx_type pad : {1, static_cast<int>(dims(k))})
`

**Comment by shsajjadi** [comment]
Thanks for reporting the bug! 
In multiple commits the reported errors and warnings and other bugs are fixed.

**Comment by damiaan** [comment]
Thanks for you efforts!

**Comment by shsajjadi** [comment]
closed
